### ISSUE TITLE
important links is Broken 

### ISSUE THREAD

**Issue by LasneF** [MicrosoftDocs/azure-docs.fr-fr#109]
the link mention 
Important
See this &gt;&gt;&gt;&gt;document&lt;&lt;&lt;&lt; for important information and tips related to OpenAPI import.
is broken 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: be16b5c5-40c4-3e6c-0b0d-840373c63f9f
* Version Independent ID: ced6b3ba-8da1-dd3d-9d1c-8a21dabd44fe
* Content: [Restrictions et problèmes connus relatifs à l’importation d’API dans la gestion des API Azure](https://docs.microsoft.com/fr-fr/azure/api-management/api-management-api-import-restrictions#feedback)
* Content Source: [articles/api-management/api-management-api-import-restrictions.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/api-management/api-management-api-import-restrictions.md)
* Service: **api-management**
* GitHub Login: @vladvino
* Microsoft Alias: **apipm**

**Comment by CeciAc** [comment]
Hello, @LasneF,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @LasneF

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/9938

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
