### ISSUE TITLE
Missing .gitattributes and .gitignore

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/azure-docs.fr-fr#193]
Noticed this because of the encoding issue  ran into from a PR. These should probably be copied from the source repo and normalize the line endings after.
/cc @ktoliver

**Comment by CeciAc** [comment]
Hello @nschonni 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by nschonni** [comment]
The currently https://github.com/MicrosoftDocs/azure-docs/blob/master/.gitattributes tells Git what typo of line endings the files should store when someone saves the file. This is important if you have authors and tools working on different platforms with different line ending preferences (Windows vs. Linux). Most of the diff in https://github.com/MicrosoftDocs/azure-docs.fr-fr/pull/192 was likely because there was mixed line endings in the file, that when changed in the web, had to be normalized to the Linux LF. The more in-dept manual for it can be found https://www.git-scm.com/docs/gitattributes

The .gitignore file tells Git what files and extensions not to track. There is a light one in the main repo https://github.com/MicrosoftDocs/azure-docs/blob/master/.gitignore

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #18926](https://github.com/MicrosoftDocs/azure-docs/issues/18926) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @nschonni 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/18926.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Thanks for the clarification, @nschonni 
@SunnyDeng can you please check this issue?

**Comment by SunnyDeng** [comment]
internal link https://ceapex.visualstudio.com/CEINTL/_queries/query/07d4cec2-19fa-4df8-93e3-3e245a74a69a/

**Comment by CeciAc** [comment]
Hi @SunnyDeng Is there any updates on this?

**Comment by CeciAc** [comment]
Hi @ishasahni1 Is there any updates on this?
@SunnyDeng
