### ISSUE TITLE
Misake

### ISSUE THREAD

**Issue by OussL** [MicrosoftDocs/azure-docs.fr-fr#196]
a small mistake in the text : "The GetTableListAndTriggerCopyData takes a list of tables as a parameter. ..."  should be "The IterateAndCopySQLTables takes a list of tables as a parameter." 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 125c8ae8-332f-8792-d81b-30bb0eb3976f
* Version Independent ID: 2e2ac8cb-4208-6692-0f25-701e4906475a
* Content: [Copier des données en bloc à l’aide d’Azure Data Factory](https://docs.microsoft.com/fr-fr/azure/data-factory/tutorial-bulk-copy-portal)
* Content Source: [articles/data-factory/tutorial-bulk-copy-portal.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/data-factory/tutorial-bulk-copy-portal.md)
* Service: **data-factory**
* GitHub Login: @linda33wj
* Microsoft Alias: **jingwang**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #19387](https://github.com/MicrosoftDocs/azure-docs/issues/19387) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @OussL 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/19387.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
