### ISSUE TITLE
Improvement for the dashboard with RBAC

### ISSUE THREAD

**Issue by MohamedKhelifi** [MicrosoftDocs/azure-docs.fr-fr#214]
Hello,

We have to add another service account for the default namespace, if not we get lot of errors on the dashboard.

Like this:
kubectl create clusterrolebinding kubernetes-dashboard --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard --serviceaccount=default:kubernetes-dashboard

Best regards.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 2ba1dad2-9792-2a7b-cdb6-68da0524cff3
* Version Independent ID: 42736112-f6db-d241-e89b-48fd2c35ceb7
* Content: [Gérer un cluster Azure Kubernetes Service avec le tableau de bord web](https://docs.microsoft.com/fr-fr/azure/aks/kubernetes-dashboard)
* Content Source: [articles/aks/kubernetes-dashboard.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/aks/kubernetes-dashboard.md)
* Service: **container-service**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #21650](https://github.com/MicrosoftDocs/azure-docs/issues/21650) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @MohamedKhelifi 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/21650.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
