### ISSUE TITLE
Missing using statement

### ISSUE THREAD

**Issue by nicolasploquin** [MicrosoftDocs/azure-docs.fr-fr#300]
In " Parse connection string " section
using Microsoft.WindowsAzure.Storage; //Namespace for CloudStorageAccount

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: a9ca205b-55ab-683a-46ee-afc9f6fc239b
* Version Independent ID: 065b8cb0-d218-b759-ce69-e8901d89b422
* Content: [Prise en main du stockage de tables Azure et de l’API Table d’Azure Cosmos DB avec .NET](https://docs.microsoft.com/fr-fr/azure/cosmos-db/table-storage-how-to-use-dotnet)
* Content Source: [articles/cosmos-db/table-storage-how-to-use-dotnet.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/cosmos-db/table-storage-how-to-use-dotnet.md)
* Service: **cosmos-db**
* GitHub Login: @wmengmsft
* Microsoft Alias: **wmeng**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25970](https://github.com/MicrosoftDocs/azure-docs/issues/25970) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @nicolasploquin 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/25970

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
