### ISSUE TITLE
Send message code

### ISSUE THREAD

**Issue by xavier-d** [MicrosoftDocs/azure-docs.fr-fr#360]
msg = Message(b'Test Message')
queue_client.send(Message("Message"))

should be

msg = Message(b'Test Message')
queue_client.send(msg)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 47bc6b40-39cd-eb95-1911-ddff96dda210
* Version Independent ID: d91a6110-e9c0-3a34-a321-6850778baaef
* Content: [Utilisation des files d’attente Azure Service Bus avec Python](https://docs.microsoft.com/fr-fr/azure/service-bus-messaging/service-bus-python-how-to-use-queues#feedback)
* Content Source: [articles/service-bus-messaging/service-bus-python-how-to-use-queues.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/service-bus-messaging/service-bus-python-how-to-use-queues.md)
* Service: **service-bus-messaging**
* GitHub Login: @axisc
* Microsoft Alias: **aschhab**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #30993](https://github.com/MicrosoftDocs/azure-docs/issues/30993) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @xavier-d 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/30993

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
