### ISSUE TITLE
StorageUri http://$storageaccountname.blob.core.windows.net/$storageContainerName/$bacpacFilename

### ISSUE THREAD

**Issue by remideprez02** [MicrosoftDocs/azure-docs.fr-fr#377]
Change http to https 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7844350b-f5a2-2c2e-5085-38e65ab41077
* Version Independent ID: a0fd06d7-67fe-3fed-b8b6-2b99cfe09412
* Content: [Exemple PowerShell d’importation d’un fichier BACPAC dans une base de données Azure SQL](https://docs.microsoft.com/fr-fr/azure/sql-database/scripts/sql-database-import-from-bacpac-powershell#feedback)
* Content Source: [articles/sql-database/scripts/sql-database-import-from-bacpac-powershell.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/sql-database/scripts/sql-database-import-from-bacpac-powershell.md)
* Service: **sql-database**
* Sub-service: **data-movement**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #31745](https://github.com/MicrosoftDocs/azure-docs/issues/31745) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @remideprez02 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/31745

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
