### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by fdebonneval** [MicrosoftDocs/azure-docs.fr-fr#404]
Hi;

Circit to be replaced by circuit in the sentence :
"ExpressRoute Local is a SKU of ExpressRoute circuit. A key feature of Local is that a Local circit"

FB

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 3cdb32c0-628d-0be2-f514-477d46dfa1b8
* Version Independent ID: fa096059-2d16-30a2-1e8b-8b9671afcaa4
* Content: [FAQ - Azure ExpressRoute](https://docs.microsoft.com/fr-fr/azure/expressroute/expressroute-faqs#expressroute-premium)
* Content Source: [articles/expressroute/expressroute-faqs.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/expressroute/expressroute-faqs.md)
* Service: **expressroute**
* GitHub Login: @jaredr80
* Microsoft Alias: **jaredro**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #32220](https://github.com/MicrosoftDocs/azure-docs/issues/32220) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @fdebonneval

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/32220

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
