### ISSUE TITLE
Storage Class for Allways on

### ISSUE THREAD

**Issue by Cedric-Bravo** [MicrosoftDocs/azure-docs.fr-fr#485]
Hi, 
I'm surprised to see RA-GRS blob storage for the cross AZ scenario.
Did you want to mention ZRS ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 15036ef6-9c0b-044e-d600-b9f90f039720
* Version Independent ID: 6fe5cd14-a1ad-e183-a048-d72686abb969
* Content: [Haute disponibilité : service Azure SQL Database](https://docs.microsoft.com/fr-fr/azure/sql-database/sql-database-high-availability#feedback)
* Content Source: [articles/sql-database/sql-database-high-availability.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/sql-database/sql-database-high-availability.md)
* Service: **sql-database**
* Sub-service: **high-availability**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **sashan**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #34315](https://github.com/MicrosoftDocs/azure-docs/issues/34315) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Cedric-Bravo

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/34315

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
