### ISSUE TITLE
Content-Type feature

### ISSUE THREAD

**Issue by dgrospelier** [MicrosoftDocs/azure-docs.fr-fr#528]
For each key, we have the ability to use a "content-type", but there is nothing about this feature in the documentation.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 876582b8-4dd5-387d-a6fd-7d9becf2968b
* Version Independent ID: d0c1fe42-3dd1-e988-b91c-8f88a4924604
* Content: [Configuration de l’application Azure FAQ](https://docs.microsoft.com/fr-fr/azure/azure-app-configuration/faq#feedback)
* Content Source: [articles/azure-app-configuration/faq.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/azure-app-configuration/faq.md)
* Service: **azure-app-configuration**
* GitHub Login: @yegu-ms
* Microsoft Alias: **yegu**

**Comment by srvbpigh** [comment]
Hello, @dgrospelier
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #35422](https://github.com/MicrosoftDocs/azure-docs/issues/35422) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @dgrospelier 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/35422

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
