### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by caronicolas** [MicrosoftDocs/azure-docs.fr-fr#538]
There's a typo on the last line of the Clean up resources, it's write " azure-front-front " but it must be " azure-vote-front "

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 65f634bf-2280-a093-5897-724310dafa2d
* Version Independent ID: f11c0af7-bfaf-6d64-2c75-9015b0eb1f30
* Content: [Didacticiel Kubernetes sur Azure - Préparer une application](https://docs.microsoft.com/fr-fr/azure/aks/tutorial-kubernetes-prepare-app#feedback)
* Content Source: [articles/aks/tutorial-kubernetes-prepare-app.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/aks/tutorial-kubernetes-prepare-app.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @caronicolas
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #35763](https://github.com/MicrosoftDocs/azure-docs/issues/35763) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @caronicolas 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/35763

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
