### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by maddentist** [MicrosoftDocs/azure-docs.fr-fr#571]
Hey, the link at the top ".NET API reference documentation" links to a 404 error page... You might want to have a look at that !

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 001b3d41-4861-9cf9-7278-bf3724f7723a
* Version Independent ID: 5d57d6ce-666a-f165-4112-0c454c577ca3
* Content: [Ressources et kit SDK de l’API .NET Table Azure Cosmos DB](https://docs.microsoft.com/fr-fr/azure/cosmos-db/table-sdk-dotnet#feedback)
* Content Source: [articles/cosmos-db/table-sdk-dotnet.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/cosmos-db/table-sdk-dotnet.md)
* Service: **cosmos-db**
* Sub-service: **cosmosdb-table**
* GitHub Login: @wmengmsft
* Microsoft Alias: **wmeng**

**Comment by srvbpigh** [comment]
Hello, @maddentist
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #37018](https://github.com/MicrosoftDocs/azure-docs/issues/37018) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @maddentist

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/37018

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
