### ISSUE TITLE
ipSecurityRestriction.ipAddress set to null?

### ISSUE THREAD

**Issue by OLoup** [MicrosoftDocs/azure-docs.fr-fr#644]
I added a virtual network subnet to the access restricted and since then I cannot deploy anymore using command lines (mvn azure-webapp:deploy). Is always says "ipSecurityRestrictions.ipAddress is required and cannot be null". I understand here that it do not recognize the vn/subnet as ip address and return an error, I guess he should not... Any solution for that?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d90bbf62-44f9-30a6-d6ea-bbf776f6efc5
* Version Independent ID: b3961eac-6c70-b345-f48c-e4c0ec67059c
* Content: [Restrictions d’accès - Azure App Service](https://docs.microsoft.com/fr-fr/azure/app-service/app-service-ip-restrictions#feedback)
* Content Source: [articles/app-service/app-service-ip-restrictions.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/app-service/app-service-ip-restrictions.md)
* Service: **app-service-web**
* GitHub Login: @ccompy
* Microsoft Alias: **ccompy**

**Comment by srvbpigh** [comment]
Hello, @OLoup
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @OLoup 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/41489

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
