### ISSUE TITLE
Undocumented field "source"

### ISSUE THREAD

**Issue by Comite-Rhone-Judo** [MicrosoftDocs/azure-docs.fr-fr#658]
Hello,
There is no mention in  the documentation to the field "source" for policy condition. Especially for sample like:
"if":{
    "allOf":[
      {
        "source":"action",
        "equals":"Microsoft.Storage/storageAccounts/write"
      },
      { 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9762f1b7-0e3a-d58f-fd99-a27ad948907b
* Version Independent ID: 89e28332-184e-ba84-df1f-e7698c5e0f7c
* Content: [Détails de la structure des définitions de stratégies - Azure Policy](https://docs.microsoft.com/fr-fr/azure/governance/policy/concepts/definition-structure#feedback)
* Content Source: [articles/governance/policy/concepts/definition-structure.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/governance/policy/concepts/definition-structure.md)
* Service: **azure-policy**
* GitHub Login: @DCtheGeek
* Microsoft Alias: **dacoulte**

**Comment by srvbpigh** [comment]
Hello, @Comite-Rhone-Judo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-maudel** [comment]
Hello, @Comite-Rhone-Judo 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43506.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
