### ISSUE TITLE
Windows 7 Pro IKEV2 support ?

### ISSUE THREAD

**Issue by sushiMix** [MicrosoftDocs/azure-docs.fr-fr#660]
[Tapez vos commentaires ici]
J'ai connecté un client windows 7 Pro à Azure via l'authentification de type certificat sur un Point to Site.
Après des ennuis avec un autre poste, j'ai constaté que le VPN utilise les ports 4500 et 500 en UDP alors qu'il s'agit des ports liés à IKEv2. SSTP utilise 443 en TCP.

Est-ce que la documentation est à jour à ce sujet ?
Est ce que windows 7 pro finalement supporte IKEv2 et SSTP ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 98d7fd30-80a8-f690-6191-d97ae4cac174
* Version Independent ID: 3e15f99b-2f2d-7adc-a2d9-0b2184989db7
* Content: [FAQ de la passerelle VPN Azure](https://docs.microsoft.com/fr-fr/azure/vpn-gateway/vpn-gateway-vpn-faq#feedback)
* Content Source: [articles/vpn-gateway/vpn-gateway-vpn-faq.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/vpn-gateway/vpn-gateway-vpn-faq.md)
* Service: **vpn-gateway**
* GitHub Login: @yushwang
* Microsoft Alias: **yushwang**

**Comment by srvbpigh** [comment]
Hello, @sushiMix
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @sushiMix 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43689

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
