### ISSUE TITLE
issue with archetype:generate in Cloud Shell 

### ISSUE THREAD

**Issue by diop-malick** [MicrosoftDocs/azure-docs.fr-fr#662]
To aovid MissingProjectException in cloud shell with Power shell you need to put quotes around every mvn command parameter like this : 

```
mvn archetype:generate "-DgroupId=example.demo" "-DartifactId=helloworld" "-DarchetypeArtifactId=maven-archetype-webapp"
```

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: c13f5f59-c119-40e6-1396-d6e65b737693
* Version Independent ID: eb8a9ad0-44fc-6e06-adb0-29df32aee19a
* Content: [Créer une application web Java sur Linux – Azure App Service](https://docs.microsoft.com/fr-fr/azure/app-service/containers/quickstart-java?toc=%2Fazure%2Fjava%2Ftoc.json&bc=%2Fazure%2Fjava%2Fbreadcrumb%2Ftoc.json&view=azure-java-stable#feedback)
* Content Source: [articles/app-service/containers/quickstart-java.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/app-service/containers/quickstart-java.md)
* Service: **app-service-web**
* GitHub Login: @msangapu
* Microsoft Alias: **msangapu**

**Comment by srvbpigh** [comment]
Hello, @diop-malick
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @diop-malick 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/44061

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
