### ISSUE TITLE
please upgrade with 2019 videos ...

### ISSUE THREAD

**Issue by ehsf973** [MicrosoftDocs/azure-docs.fr-fr#663]
This is a link to a video on Channel 9 from the 2015 MS Ignite conference. 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 732eb4b2-7efe-02a0-b905-fe03f9c94e84
* Version Independent ID: 64b0f82c-2d46-92c5-37f7-5e06596171b9
* Content: [Guide de sécurité Azure Storage](https://docs.microsoft.com/fr-fr/azure/storage/common/storage-security-guide)
* Content Source: [articles/storage/common/storage-security-guide.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/storage/common/storage-security-guide.md)
* Service: **storage**
* Sub-service: **common**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by srvbpigh** [comment]
Hello, @ehsf973
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ehsf973

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/44313

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
