### ISSUE TITLE
do some schemes for the flow processing 

### ISSUE THREAD

**Issue by ehsf973** [MicrosoftDocs/azure-docs.fr-fr#668]
for this part 

"A side effect is that if an outbound flow from a VM in the back-end pool attempts a flow to front ........  to any other VM in the back-end pool, the halves of the flow do match and the VM can respond to the flow."

could you do some schemes with arrows for the flows information ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7eaaf7c7-c1fe-1afc-e7f8-bc0e90044fb8
* Version Independent ID: 6461936a-3f5d-c2fe-cb37-e40fc9dc929e
* Content: [Qu’est-ce qu’Azure Load Balancer ? - Azure Load Balancer](https://docs.microsoft.com/fr-fr/azure/load-balancer/load-balancer-overview?source=docs)
* Content Source: [articles/load-balancer/load-balancer-overview.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/load-balancer/load-balancer-overview.md)
* Service: **load-balancer**
* GitHub Login: @asudbring
* Microsoft Alias: **allensu**

**Comment by srvbpigh** [comment]
Hello, @ehsf973
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by mchikhaoui** [comment]
<.p12 key path on the IR machine> ,

what is IR machine ?

**Comment by srvbpigh** [comment]
Hello, @ehsf973, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/45363. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
