### ISSUE TITLE
Details on Azure AD admin accounts supported

### ISSUE THREAD

**Issue by bsocca** [MicrosoftDocs/azure-docs.fr-fr#671]
Hi,
For the O365 MFA & Security Default offers, could you detail what you mean exactly by Azure AD admin accounts ?
All users with an Azure AD role are included (Guest Inviter, Reports Reader, etc.) ? Does it work for custom role also ?
Could you confirm that it is limited to Azure AD roles and not Azure roles ? 
Regards,

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: feb03e63-f543-d85b-9daf-16b4d1e13a60
* Version Independent ID: da9dcdd2-70d4-e08e-18f2-6e6a1489937a
* Content: [Versions Azure MFA et plans de consommation - Azure Active Directory](https://docs.microsoft.com/fr-fr/azure/active-directory/authentication/concept-mfa-licensing#feedback)
* Content Source: [articles/active-directory/authentication/concept-mfa-licensing.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/authentication/concept-mfa-licensing.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by srvbpigh** [comment]
Hello, @bsocca
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @bsocca, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/45887. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
