### ISSUE TITLE
vhds virtual size maximum

### ISSUE THREAD

**Issue by ehsf973** [MicrosoftDocs/azure-docs.fr-fr#673]
"All VHDs on Azure must have a virtual size aligned to 1MB."
isn't it 1,023 Gbs ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 1b9c0d7a-bbf5-eccc-f2ca-a825bf42c82f
* Version Independent ID: 58aa93af-4030-1541-a14c-c66c683ccf7c
* Content: [Préparer un disque dur virtuel Windows à charger sur Azure](https://docs.microsoft.com/fr-fr/azure/virtual-machines/windows/prepare-for-upload-vhd-image?source=docs)
* Content Source: [articles/virtual-machines/windows/prepare-for-upload-vhd-image.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/virtual-machines/windows/prepare-for-upload-vhd-image.md)
* Service: **virtual-machines-windows**
* GitHub Login: @glimoli
* Microsoft Alias: **genli**

**Comment by ehsf973** [comment]
or we must understand that the min is 1MB and the max is 1,023Gbs.  meaning multiple of 1 MB ?

**Comment by srvbpigh** [comment]
Hello, @ehsf973
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @ehsf973, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/46123. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
