### ISSUE TITLE
unable to find parameter 'LeafBase'

### ISSUE THREAD

**Issue by ynguyenluat** [MicrosoftDocs/azure-docs.fr-fr#679]
When executing the az module code: Deploy-AzTemplate.ps1 -ArtifactStagingDirectory . -Location centralus -TemplateFile WebSite.json -TemplateParametersFile WebSite.parameters.json, I got the error: unable to find parameter 'LeafBase' with powershell version 5.1.18362

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 640c3387-4a7e-71d6-5c53-43ad28b65234
* Version Independent ID: 62ac189f-ef81-48d2-b726-d51fa3c3262b
* Content: [Créer et déployer des projets de groupe de ressources avec Visual Studio](https://docs.microsoft.com/fr-fr/azure/azure-resource-manager/templates/create-visual-studio-deployment-project#feedback)
* Content Source: [articles/azure-resource-manager/templates/create-visual-studio-deployment-project.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/azure-resource-manager/templates/create-visual-studio-deployment-project.md)

**Comment by srvbpigh** [comment]
Hello, @ynguyenluat
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #46982](https://github.com/MicrosoftDocs/azure-docs/issues/46982) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @ynguyenluat, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/46982. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
