### ISSUE TITLE
Azure AD admin

### ISSUE THREAD

**Issue by Sbou** [MicrosoftDocs/azure-docs.fr-fr#697]
Hello,

Is it possible to set the AD admin user or group by API or az CLI ?
If not, is it scheduled ?

Thanks,

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f87e092b-c331-8bc9-9061-89f0712adb5a
* Version Independent ID: d0ef3b6e-5973-e159-3c73-9eb8dbf2825f
* Content: [Utiliser Azure Active Directory - Azure Database pour PostgreSQL - Serveur unique](https://docs.microsoft.com/fr-fr/azure/postgresql/howto-configure-sign-in-aad-authentication#feedback)
* Content Source: [articles/postgresql/howto-configure-sign-in-aad-authentication.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/postgresql/howto-configure-sign-in-aad-authentication.md)
* Service: **postgresql**
* GitHub Login: @lfittl
* Microsoft Alias: **lufittl**

**Comment by srvbpigh** [comment]
Hello, @Sbou
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @Sbou, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/50913. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
