### ISSUE TITLE
At Run examples from your IDE, the python example has 'python' written in the first line before the imports.

### ISSUE THREAD

**Issue by diogobaltazar** [MicrosoftDocs/azure-docs.fr-fr#699]
[Tapez vos commentaires ici]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 3642022f-a58f-6290-ecf1-3c551a9bfc96
* Version Independent ID: cf117e4e-c261-858c-517e-04d67e44c35e
* Content: [Databricks Connect-Azure Databricks](https://docs.microsoft.com/fr-fr/azure/databricks/dev-tools/databricks-connect?source=docs#feedback)
* Content Source: [databricks/dev-tools/databricks-connect.md](https://github.com/MicrosoftDocs/databricks-pr.fr-FR/blob/live/databricks/dev-tools/databricks-connect.md)
* Service: **azure-databricks**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by srvbpigh** [comment]
Hello, @diogobaltazar
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #51466](https://github.com/MicrosoftDocs/azure-docs/issues/51466) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @diogobaltazar, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/51466. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
