### ISSUE TITLE
Domain verification id from my app

### ISSUE THREAD

**Issue by dumaisf** [MicrosoftDocs/azure-docs.fr-fr#708]
Where can I find my domain verification id from my app in azure? (domain-verification-id-from-your-app)

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: 224b73dd-c59d-a833-0d4d-a778af6086a9
* Version Independent ID: c6b167c9-9589-45d0-ee6a-7a47a4aec41e
* Content: [Tutoriel : Mapper un nom DNS personnalisé existant](https://docs.microsoft.com/fr-ca/azure/app-service/app-service-web-tutorial-custom-domain#map-your-domain)
* Content Source: [articles/app-service/app-service-web-tutorial-custom-domain.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/app-service/app-service-web-tutorial-custom-domain.md)
* GitHub Login: @OpenLocalizationService

**Comment by srvbpigh** [comment]
Hello, @dumaisf
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54009](https://github.com/MicrosoftDocs/azure-docs/issues/54009) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @dumaisf, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/54009. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
